name: 'Lint pipeline'


on:
  workflow_dispatch: # To can dispatch manually

  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main

  push: # First pipeline to run when deploy a new version
    branches:
      - main


env:
  BASE_IMAGE_NAME: 'test-python-api'


jobs:

  lint-analysis:
    name: "Lint Analysis"
    runs-on: ubuntu-latest

    steps:
    - name: Obtendo o código fonte
      uses: actions/checkout@v4.2.2

    - name: 'Create reports directory'
      run: mkdir reports

    - name: 'Dockerfile Lint'
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./Dockerfile
        no-fail: true
        output-file: reports/dockerfile-lint-report.sarif
        format: sarif

    - name: 'Upload lint report'
      uses: actions/upload-artifact@v4
      with:
        path: reports
        name: dockerfile-lint-report

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v3

    - name: Build Docker
      run: |
        docker build -f ./Dockerfile . -t ${{ env.BASE_IMAGE_NAME }}:latest

    - name: 'Docker show image'
      run: docker image ls

    - name: 'Scan Docker image'
      uses: aquasecurity/trivy-action@0.32.0
      with:
        image-ref: ${{ env.BASE_IMAGE_NAME }}:latest
        format: 'sarif'
        exit-code: 0
        scan-type: 'image'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        output: 'reports/trivy-dockerimage-results.sarif'

    - name: 'Upload trivy report'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: reports
        category: tools
