name: 'Deploy Project'


on:
  workflow_dispatch: # To can dispatch manually

  release:
    types: [created]
    tags: ["v*.*.*"]
    branches:
    - main


concurrency:
  group: ci-${{ github.repository }}
  cancel-in-progress: true

env:
  BASE_IMAGE_NAME: 'test-python-api'


jobs:
  build:
    name: 'Building Docker Image'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4.1.2

    - name: 'Get tag'
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v3

    - name: Build Docker
      run: |
        docker build -f ./Dockerfile . -t ${{ env.BASE_IMAGE_NAME }}:${{ steps.tag.outputs.tag }}

    - name: 'Save Docker Image'
      run: |
        docker save -o ${{ env.BASE_IMAGE_NAME }}.tar ${{ env.BASE_IMAGE_NAME }}:${{ steps.tag.outputs.tag }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BASE_IMAGE_NAME }}
        path: ${{ env.BASE_IMAGE_NAME }}.tar
        retention-days: 1



  dev-release:
    name: 'Publish Docker Image to GitHub Container Registry'
    runs-on: ubuntu-latest
    environment: DEV
    needs: build
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      packages: write

    steps:

    - name: 'Download artifact'
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.BASE_IMAGE_NAME }}

    - name: 'Get tag'
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v3

    - name: 'Log in to Docker Hub'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Load & Push Docker Image
      run: |
        docker load -i ${{ env.BASE_IMAGE_NAME }}.tar

    - name: 'Add Docker Image Tags'
      run: |
        docker tag ${{ env.BASE_IMAGE_NAME }}:${{ steps.tag.outputs.tag }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
        docker tag ${{ env.BASE_IMAGE_NAME }}:${{ steps.tag.outputs.tag }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: 'Push Docker Image to GitHub Container Registry'
      run: |
        docker push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}




  prod-release:
    name: 'Publish Docker Image to Docker Hub'
    runs-on: ubuntu-latest
    environment: PROD
    needs: dev-release

    steps:

    - name: 'Download artifact'
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.BASE_IMAGE_NAME }}

    - name: 'Get tag'
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v3

    - name: 'Log in to Docker Hub'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Load & Push Docker Image
      run: |
        docker load -i ${{ env.BASE_IMAGE_NAME }}.tar

    - name: 'Add Docker Image Tags'
      run: |
        docker tag ${{ env.BASE_IMAGE_NAME }}:${{ steps.tag.outputs.tag }} ${{ secrets.DOCKERHUB_USERNAME  }}/${{ env.BASE_IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
        docker tag ${{ env.BASE_IMAGE_NAME }}:${{ steps.tag.outputs.tag }} ${{ secrets.DOCKERHUB_USERNAME  }}/${{ env.BASE_IMAGE_NAME }}:latest

    - name: 'Push Docker Image to GitHub Container Registry'
      run: |
        docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME  }}/${{ env.BASE_IMAGE_NAME }}
