name: 'Versioning'


on:
  workflow_dispatch: # To can dispatch manually

  push: # First pipeline to run when deploy a new version
    branches:
      - main
    paths:
      - "src/**"
      - 'Dockerfile'
      - 'requirements.txt'


jobs:

  build:
    name: "Build Image"
    runs-on: 'ubuntu-latest'

    steps:

    - name: "Checkout"
      uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Semantic Release
      id: 'semantic-release'
      uses: cycjimmy/semantic-release-action@v4.2.2
      with:
        semantic_version: 22.0.8
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "New version"
      run: |
        echo "Published new version: ${{ steps.semantic-release.outputs.new_release_published }}"
        echo "New version: ${{ steps.semantic-release.outputs.new_release_version }}"
